name: CONTINOUS DEPLOYMENT

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_DEVELOPMENT }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.IP_DEVELOPMENT }} >> ~/.ssh/known_hosts

      - name: Deploy To AWS Development Server
        run: |
          echo 'Starting to Deploy...'
          ssh ubuntu@${{ secrets.IP_DEVELOPMENT }} "
          echo 'Pulling new updated server'
          cd /var/ww/html/food-app/ && git pull origin main
          echo 'Composer Install'
          composer install
          echo 'migration'
          php artisan migrate
          echo 'composer auotoload'
          composer dump-autoload
          "
          echo 'Deployment completed successfully'
